version: '3'

networks:
  my_network2:
    driver: bridge

volumes:
  volume_postgres:

services:
  postgres:
    image: postgres
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: gestion_abonnement
    ports:
      - "5433:5432"
    volumes:
      - volume_postgres:/var/lib/postgresql/data
    networks:
      - my_network2

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring_application
    restart: always
    depends_on:
      - postgres
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/gestion_abonnement
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - my_network2
